---
title: "homework4"
output: html_document
date: "2023-10-24"
---


### read in global gender inequality data

```{r}
InequalityData <- read.csv("/Users/qiaoy/Desktop/Geographic Information Systems and Science/wk4/homework/HDR21-22_Composite_indices_complete_time_series.csv", 
                         sep = ",",  
                         encoding = "latin1")
```


### creating a new column of difference in inequality between 2010 and 2019

```{r}
library(dplyr)
InequalityData <- InequalityData %>%
  dplyr::select(c("country", "gii_2010":"gii_2019")) %>%
  mutate(diff_inequality = gii_2010 - gii_2019)
head(InequalityData, 5)
```


### read in spatial data of the World

```{r}
library(sf)
library(tmap)
WorldMap <- st_read("/Users/qiaoy/Desktop/Geographic Information Systems and Science/wk4/homework/World_Countries_Generalized/World_Countries_Generalized.shp")
qtm(WorldMap)
```


### join csv and map

```{r}
InequalityMap <- WorldMap %>%
  left_join(., 
            InequalityData,
            by = c("COUNTRY" = "country"))
InequalityMap
```


### mapping

```{r}
library(tmaptools)
tmap_mode("plot")
qtm(InequalityMap, 
    fill = "diff_inequality")
```
